### ISSUE TITLE
[Place 30-172] Sub-optimal placement for a clock-capable IO pin and PLL pair.

### ISSUE THREAD

**Issue by JonasDann** [hamsternz/ArtyEtherentTX#1]
Hi, thanks for your great work.

I get this error, when Vivado tries to place the design:

[Place 30-172] Sub-optimal placement for a clock-capable IO pin and PLL pair. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
    < set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK100MHZ_IBUF] >

```
CLK100MHZ_IBUF_inst (IBUF.O) is locked to IOB_X1Y76
 clocking (PLLE2_ADV.CLKIN1) is provisionally placed by clockplacer on PLLE2_ADV_X0Y1

The above error could possibly be related to other connected instances. Following is a list of 
all the related clock rules and their respective instances.

Clock Rule: rule_pll_clklds
Status: PASS 
Rule Description: A PLL driving any number of IOBs must be placed within the same clock region
 clocking (PLLE2_ADV.CLKOUT0) is provisionally placed by clockplacer on PLLE2_ADV_X0Y1
 and clock_fwd_ddr (ODDR.C) is locked to OLOGIC_X0Y56
```

Is this only a problem for me or do I have to do something more than open the project in Vivado to get it to work?

Greetings

**Comment by JonasDann** [comment]
I got it onto my Arty with these two lines added to the .xdc file:

set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets CLK100MHZ_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK100MHZ_IBUF]

But it still does not work for me. I have added the ip and mac that I entered for the FPGA in the arp table of my Laptop. I have connected them via a crossover cable and also tried a non crossover LAN cable. The yellow led on the NIC is blinking really fast when I turn up the transmission rate with the switches, but I can not see anything in Wireshark. There are only the packets sent by the Laptop.

**Comment by JonasDann** [comment]
I feel kind of dumb now, but hey it works. I just set my UDP Receiver application to receive on port 4096. 

Of course the problem [Place 30-172] still exists.

**Comment by hamsternz** [comment]
Hi!

Grrr Vivado 2016.1 has broken the automatic insertion of a global clock 
buffer on the input.

I've fixed it and pushed the change.

https://github.com/hamsternz/ArtyEtherentTX/commit/4f7e6594dbf971857d2830283bcca22025eb163c

Just needed to add a global clock buffer (BUFG) for the 100MHz clock the 
way into the PLL.

Mike

**Comment by hamsternz** [comment]
:-)

Mike

**Comment by JonasDann** [comment]
I can confirm that the fix works for me too. I will close the issue.

Jonas
